import Image from 'next/image'
import Thanks from '../../public/thanks.webp'
import { Oxygen } from 'next/font/google'
import Head from 'next/head'
import { MainContainer, TextContent } from '@/styles/thankspage.styles'

const Vietnam = Oxygen({
  subsets: ['latin'],
  weight: ['300', '400', '700'],
})

export default function ThanksPage() {
  return (
    <>
      <Head>
        <title>Obrigado Pela Compra</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo2.png" />
        <script
          src="https://cdn.utmify.com.br/scripts/utms/latest.js"
          async
          defer
        ></script>
      </Head>
      <MainContainer className={Vietnam.className}>
        <Image alt="logo" src={Thanks} quality={100} />{' '}
        <TextContent>
          <h1>Parabéns Pela Compra Do App!</h1>
          <p>será enviado para seu e-mail o acesso. Muito fácil de acessar!</p>

          <p>
            Aproveite esta oportunidade! E memorize uma coisa: Tudo depende de
            você! A culpa sempre será sua por estar onde você está.
          </p>
          <p>Boa sorte, ShopeeCash</p>
        </TextContent>
      </MainContainer>
    </>
  )
}
